### ISSUE TITLE
Generator - неправильное название

### ISSUE THREAD

**Issue by mordvinx** [Mikhail-Martynenko/brain-train-react#2]
https://github.com/Mikhail-Martynenko/brain-train-react/blob/67d5747ce96d6eff9cc2b51e221acb9880872153/src/domain/taskGenerator.ts#L4C32-L4C41

Не нужно называть класс как `Generator`, уже есть [function*](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*)

`interface TaskGenerator` 

`TaskGeneratorImpl implements TaskGenerator`

**Comment by Mikhail-Martynenko** [comment]
Закрыл
